#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

require 'tmpdir'
require 'optparse'
require "unicode_utils/upcase"

def batch_latex(options)
  latex_code(options)
end

def latex_code(options)
  DATA.readlines.join('').tap { |tex|
    tex.gsub!(/@@NAME@@/) { t( options[:one] + " " + options[:three]) }
    tex.gsub!(/@@WIFI_CODE@@/) { options[:wifi_code] }
    tex.gsub!(/@@QR_CODE_FILE@@/) { options[:qr_code_file] }
    tex.gsub!(/@@INSTALL_DIR@@/) { options[:install_dir] }
  }
end

def t(string)
  string.tap { |str|
    str.gsub!(/([\{\}])/) { |m| "\\#{m}" }
    str.gsub!(/\\/) { '\\textbackslash{}' }
    str.gsub!(/\^/) { '\\textasciicircum{}' }
    str.gsub!(/\~/) { '\\textasciitilde{}' }
    str.gsub!(/\|/) { '\\textbar{}' }
    str.gsub!(/\</) { '\\textless{}' }
    str.gsub!(/\>/) { '\\textgreater{}' }
    str.gsub!(/([\_\$\#\&\%])/) { |m| "\\#{m}" }
    # Comment in in case of paranoia:
    # str.gsub!(/[^a-zA-Z0-9äöüÄÖÜßøØæÆ»«¢©]\\\/\^\~\|\<\>\_\$\{\}\#\&\%/, '')
  }
end

options = { :vip => false, :two_days => false, :debug => false, :output => nil }
options.default = ''
OptionParser.new do |opts|
  opts.banner = "Usage: #{$0} [options]"

  opts.on("-f", "--firstname FIRSTNAME", "") do |val|
    options[:one] = val
  end
  opts.on("-s", "--secondname [SECONDNAME]", "") do |val|
    options[:two] = val
  end
  opts.on("-l", "--lastname LASTNAME", "") do |val|
    options[:three] = val
  end
  opts.on("-c", "--company COMPANY", "") do |val|
    options[:company] = val
  end

  opts.on("-w", "--wifi_code WIFI-CODE", "") do |val|
    options[:wifi_code] = val
  end
  opts.on("-q", "--qr_code_file FILE", "") do |val|
    options[:qr_code_file] = val
  end
  opts.on("-o", "--output FILE", "") do |val|
    options[:output] = val
  end  
  opts.on("-d", "--[no-]debug", "") do |val|
    options[:debug] = val
  end  
  opts.on("-p", "--printer NAME", "") do |val|
    options[:printer] = val
  end  
end.parse!

TexFileName = 'wificode.tex'
PdfFileName = 'wificode.pdf'
OutFileName = 'wificode.out'
InstallDir = File.expand_path(File.dirname(__FILE__))

options[:install_dir] = InstallDir

puts "Options:"+options.inspect();

Dir.mktmpdir { |tmp|
  p = Dir.pwd
  Dir.chdir(tmp)
  File.open(TexFileName, 'w') do |f|
    f.puts batch_latex(options)
  end

  system("pdflatex -halt-on-error #{TexFileName} > #{OutFileName}")

  if options[:printer] 
    system("lpr -P#{options[:printer]} #{PdfFileName}")
  else
		if options[:output]
			system("cp #{PdfFileName} #{p}/#{options[:output]}")
		elsif options[:debug]
			system("cat #{OutFileName}")    
		else
			system("cat #{PdfFileName}")
		end
  end
}



__END__
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{graphics}
\usepackage{color}
%\usepackage{pst-barcode}
\usepackage{ifthen}

\pagestyle{empty}

\setlength{\voffset}{-1in}
\setlength{\hoffset}{-1in}
\setlength{\textwidth}{210mm}
\setlength{\textheight}{297mm}
\setlength{\topmargin}{30mm}
\setlength{\leftmargin}{30mm}
\setlength{\oddsidemargin}{30mm}
\setlength{\evensidemargin}{30mm}
\setlength{\headheight}{0cm}
\setlength{\headsep}{0cm}
\setlength{\parsep}{0cm}
\setlength{\parindent}{0cm}

\definecolor{blue}{cmyk}{1, 0.27, 0, 0.06}

\newcommand{\wificode}[4]{%
  \W{#1}{#2}{#3}{#4}
  \newpage
}

\newcommand{\W}[4]{%
  \parbox{150mm}{%
    \includegraphics{#3/next_berlin_logo}\hfill\includegraphics{#3/drei_sechs_null_logo}%

    \rule{0mm}{20mm}%

    \fontsize{20}{24} \sffamily \bfseries \centerline {#4}

    \centerline{\resizebox{1in}{!}{\includegraphics{#2}}}

    \fontsize{28}{30} \sffamily \bfseries \centerline{#1}

    \fontsize{20}{24} \sffamily \bfseries \centerline wifi.nextconf.eu/{#1}
  }
}

\begin{document}
   \wificode{@@WIFI_CODE@@}{@@QR_CODE_FILE@@}{@@INSTALL_DIR@@}{@@NAME@@}
\end{document} 
